// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enrctsghtmdgzkpyhsrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVucmN0c2dodG1kZ3prcHloc3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTcwNjksImV4cCI6MjA1NzQ3MzA2OX0.b9J4D33pTodWbP3cmv7uLY5X69UPoOepTYwyjefINJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);