// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubkporifsquqlygysyly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVia3Bvcmlmc3F1cWx5Z3lzeWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwOTk5MDYsImV4cCI6MjA5MTY3NTkwNn0.R8j6UV1cKK0VKTsyOzpmp5XyZPK4Dr6h2EWMm-sr60s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});