// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrafbobknfkbkueyvkrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYWZib2JrbmZrYmt1ZXl2a3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODg3MzksImV4cCI6MjA1NzQ2NDczOX0.HoSysJlGzVPC6DNNa9TaAWUnefSDOvAbE4dje0sNZ8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);